version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: requi_feed_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: requi_feed
    ports:
      - "5433:5432"
